services:
  backend:
    image: backend
    build:
      context: ./Backend
      dockerfile: /API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - vault 
       
       
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/data:/vault/data
      - ./vault:/vault/config
    command: [ "server"]
    
    
  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8000:80"