services:
  backend:
    image: backend
    build:
      context: ./Backend
      dockerfile: /API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=https://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mysslpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./aspnetapp.pfx
    volumes:
      - ./vault_keys.json:/app/vault_keys.json
      - ./certs/aspnetapp.pfx:/app/aspnetapp.pfx
    depends_on:
      - vault
      - database
       
       
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/data:/vault/data
      - ./vault:/vault/config
    command: [ "server"]
    
    
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - db_data:/var/opt/mssql
    depends_on:
      - vault
    
  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8001:80"
      - "8000:443"
  
  
volumes:
  db_data: