services:
  backend:
    image: backend
    build:
      context: ./Backend
      dockerfile: /API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - vault 
       
       
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/data:/vault/data
      - ./vault:/vault/config
    command: [ "server"]
    
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Password"
      ACCEPT_EULA: "Y"
    volumes:
      - db_data:/var/opt/mssql
    
  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8000:80"
  
volumes:
  db_data: